config/routes.rb
RailsRumble::Application.routes.draw do
  resources :strategies

  root :to => "welcome#index"

end

app/models/strategy.rb
class Strategy < ActiveRecord::Base
  DIVISIONS = ['Bronze','Silver','Gold','Platinum','Diamond','Master','Grandmaster']
  RACES = ['terran','protoss','zerg']  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  def index
    @strategies = Strategy.all
  end

  def show
    @strategy = Strategy.find(params[:id])
  end

  def new
    @strategy = Strategy.new
  end

  def create
    @strategy = Strategy.new(params[:strategy])
    if @strategy.save
      redirect_to @strategy, :notice => "Successfully created strategy."
    else
      render :action => 'new'
    end
  end

  def edit
    @strategy = Strategy.find(params[:id])
  end

  def update
    @strategy = Strategy.find(params[:id])
    if @strategy.update_attributes(params[:strategy])
      redirect_to @strategy, :notice  => "Successfully updated strategy."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @strategy = Strategy.find(params[:id])
    @strategy.destroy
    redirect_to strategies_url, :notice => "Successfully destroyed strategy."
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    bnet_url = params[:bnet_url] || 'http://us.battle.net/sc2/en/profile/789884/1/dSeleCT/'
    @sc2ranks = Sc2ranks.new('malayancolleges.com')
    @character = @sc2ranks.character(bnet_url)
    if @character.team(1)
      @t1strategies = Strategy.find(:all, :conditions => ["? between range_low and range_high and LOWER(race) = ? and LOWER(league) = ?", @character.team(1).points, @character.team(1).fav_race.downcase, @character.team(1).league.downcase])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bracket_identifier(bracket)
    identifier =  case bracket
    when "1"
      "1v1"
    when "2"
      "2v2"
    when "3"
      "3v3"
    when "4"
      "4v4"
    else
      "FFA"
    end
    return identifier
  end
  
  def strategy_lists(character)
    
    strategies
  end
  
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/strategies_helper.rb
module StrategiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/strategies/_form.html.erb
<%= form_for @strategy do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :race %><br />
    <%= f.select :race, options_for_select(Strategy::RACES) %>
  </p>
  <p>
    <%= f.label :range_low %><br />
    <%= f.text_field :range_low %>
  </p>
  <p>
    <%= f.label :range_high %><br />
    <%= f.text_field :range_high %>
  </p>
  <p>
    <%= f.label :league %>
    <%= f.select :league, options_for_select(Strategy::DIVISIONS)%>
  </p>  
  <p>
    <%= f.label :play_style %><br />
    <%= f.text_field :play_style %>
  </p>
  
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :build_order %><br />
    <%= f.text_area :build_order %>
  </p>
  <p>
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </p>  
  <p><%= f.submit %></p>
<% end %>

app/views/strategies/edit.html.erb
<% title "Edit Strategy" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @strategy %> |
  <%= link_to "View All", strategies_path %>
</p>

app/views/strategies/index.html.erb
<% title "Strategies" %>

<table>
  <tr>
    <th>Name</th>
    <th>Range Low</th>
    <th>Range High</th>
    <th>League</th>
    <th>Race</th>
    <th>Play Style</th>
  </tr>
  <% for strategy in @strategies %>
    <tr>
      <td><%= strategy.name %></td>
      <td><%= strategy.range_low %></td>
      <td><%= strategy.range_high %></td>
      <td><%= strategy.league %></td>      
      <td><%= strategy.race %></td>
      <td><%= strategy.play_style %></td>
      <td><%= link_to "Show", strategy %></td>
      <td><%= link_to "Edit", edit_strategy_path(strategy) %></td>
      <td><%= link_to "Destroy", strategy, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Strategy", new_strategy_path %></p>

app/views/strategies/new.html.erb
<% title "New Strategy" %>

<%= render 'form' %>

<p><%= link_to "Back to List", strategies_path %></p>

app/views/strategies/show.html.erb
<% title "Strategy" %>

<p>
  <strong>Name:</strong>
  <%= @strategy.name %>
</p>
<p>
  <strong>Race:</strong>
  <%= @strategy.race %>
</p>
<p>
  <strong>League</strong>
  <%= @strategy.league %>
</p>
<p>
  <strong>Range Low:</strong>
  <%= @strategy.range_low %>
</p>
<p>
  <strong>Range High:</strong>
  <%= @strategy.range_high %>
</p>
<p>
  <strong>Link:</strong>
  <%= @strategy.link %>
</p>
<p>
  <strong>Description:</strong>
  <%=simple_format @strategy.description %>
</p>
<p>
  <strong>Build Order:</strong>
  <%=simple_format @strategy.build_order %>
</p>

<p>
  <strong>Play Style:</strong>
  <%= @strategy.play_style %>
</p>

<p>
  <%= link_to "Edit", edit_strategy_path(@strategy) %> |
  <%= link_to "Destroy", @strategy, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", strategies_path %>
</p>

app/views/welcome/index.html.erb
<%#= @character.inspect %>
<%= form_tag ('/'), :method => 'post' do %>
Battle.net Profile URL <%= text_field_tag 'bnet_url' %>
<%= submit_tag "Submit" %>
<% end%>
<div>
  <br>
  Name : <%= @character.name %>
  <br>
  Character Code : <%= @character.character_code %>
  <br>
  Region : <%= @character.region %>
  <br>
  BNET ID : <%= @character.bnet_id %>
  <br>
</div>
<br>
<% if @character.team(1) %>
  <div style="border:1px solid black">
    <strong>1v1</strong>
    <br>
    Division : <%= @character.team(1).division %>
    <br>
    Division Rank : <%= @character.team(1).division_rank %>
    <br>
    Points : <%= @character.team(1).points %>
    <br>
    Wins : <%= @character.team(1).wins %>
    <br>
    Losses : <%= @character.team(1).losses %>
    <br>
    W/L Ratio : <%= @character.team(1).ratio %>
    <br>
    World Rank : <%= @character.team(1).world_rank %>
    <br>
    League : <%= @character.team(1).league%>
    <br>
    Race : <%= @character.team(1).fav_race %>
    <br>
    <br>
    <strong>Recommended Build Orders for your Division and Score</strong>
    <ul>
    <% @t1strategies.each do |strategy| %>
      <li><%= link_to strategy.name, strategy_path(strategy) %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if @character.team(2) %>
  <% @character.team(2).each do |team| %>
    <div style="border:1px solid black">
      <strong>2V2</strong>
      <br>
      Division : <%= team.division %>
      <br>
      Division Rank : <%= team.division_rank %>
      <br>
      Points : <%= team.points %>
      <br>
      Wins : <%= team.wins %>
      <br>
      Losses : <%= team.losses %>
      <br>
      W/L Ratio : <%= team.ratio %>
      <br>
      World Rank : <%= team.world_rank %>
      <br>
      League : <%= team.league%>
      <br>
      Race : <%= team.fav_race %>
      <br>
    </div>
  <% end %>
<% end %>